# Homework 4

For this assignment, you will be developing an artificial neural network to classify data given in the __[Dry Beans Data Set](https://archive.ics.uci.edu/ml/datasets/Dry+Bean+Dataset#)__. This data set was obtained as a part of a research study by Selcuk University, Turkey, in which a computer vision system was developed to distinguish seven different registered varieties of dry beans with similar features. More details on the study can be found in the following __[research paper](https://www.sciencedirect.com/science/article/pii/S0168169919311573)__. <br>
### **Make sure to use the lecture notebook on an introduction to keras and cross validation located [here](https://colab.research.google.com/drive/1ksEGL7SJ_wutCIyPYx7Loe5EPdOij6dJ?usp=sharing) and [here](https://colab.research.google.com/drive/1C9Mwf1J2ril1Q4l6n2BjQMb8YaFySG5_?usp=sharing)**.

## About the Data Set
Seven different types of dry beans were used in a study in Selcuk University, Turkey, taking into account the features such as form, shape, type, and structure by the market situation. A computer vision system was developed to distinguish seven different registered varieties of dry beans with similar features in order to obtain uniform seed classification. For the **classification** model, images of 13611 grains of 7 different registered dry beans were taken with a high-resolution camera. Bean images obtained by computer vision system were subjected to segmentation and feature extraction stages, and a total of 16 features - 12 dimensions and 4 shape forms - were obtained from the grains.

Number of Instances (records in the data set): __13611__

Number of Attributes (fields within each record, including the class): __17__

### Data Set Attribute Information:

1. __Area (A)__ : The area of a bean zone and the number of pixels within its boundaries.
2. __Perimeter (P)__ : Bean circumference is defined as the length of its border.
3. __Major axis length (L)__ : The distance between the ends of the longest line that can be drawn from a bean.
4. __Minor axis length (l)__ : The longest line that can be drawn from the bean while standing perpendicular to the main axis.
5. __Aspect ratio (K)__ : Defines the relationship between L and l.
6. __Eccentricity (Ec)__ : Eccentricity of the ellipse having the same moments as the region.
7. __Convex area (C)__ : Number of pixels in the smallest convex polygon that can contain the area of a bean seed.
8. __Equivalent diameter (Ed)__ : The diameter of a circle having the same area as a bean seed area.
9. __Extent (Ex)__ : The ratio of the pixels in the bounding box to the bean area.
10. __Solidity (S)__ : Also known as convexity. The ratio of the pixels in the convex shell to those found in beans.
11. __Roundness (R)__ : Calculated with the following formula: (4piA)/(P^2)
12. __Compactness (CO)__ : Measures the roundness of an object: Ed/L
13. __ShapeFactor1 (SF1)__
14. __ShapeFactor2 (SF2)__
15. __ShapeFactor3 (SF3)__
16. __ShapeFactor4 (SF4)__

17. __Classes : *Seker, Barbunya, Bombay, Cali, Dermosan, Horoz, Sira*__

### Libraries that can be used :
- NumPy, SciPy, Pandas, Sci-Kit Learn, TensorFlow, Keras. You may also use PyTorch (though support may be limited)
- Any other library used during the lectures and discussion sessions.

### Other Notes
- Don't worry about not being able to achieve high accuracy, it is neither the goal nor the grading standard of this assignment.
- Discussion and Lecture materials should be helpful for doing the assignments.
- The homework submission should be a .ipynb file.


In [62]:
# !git clone https://github.com/ucsd-cse151a-ss25/hw4.git


## Exercise 1 : Building a Feed-Forward Neural Network(50 points)

### Exercise 1.1 : Data Preprocessing (10 points)

- As the classes are categorical, use one-hot encoding to represent the set of classes. You will find this useful when developing the output layer of the neural network.
- Split the data into training and testing set by __90:10__ and use the training set for training the model and the test set to evaluate the model performance. Please set verbose=0 to suppress output during training.
- Normalize each field of the input data using the min-max normalization technique.

__Notes:__

- Splitting of the dataset should be done __before__ the normalization step and __after__ the one-hot encoding.

In [63]:
import pandas as pd
import numpy as np

In [64]:
df= pd.read_csv('Dry_Beans_Dataset.csv')

In [65]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler

In [66]:
X=df.iloc[:,:-1]
X

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0       44830    814.955       320.731947       178.405838      1.797766   
1       33476    691.826       258.837971       165.220760      1.566619   
2       27057    606.138       227.460904       151.860320      1.497830   
3       49483    844.283       326.602913       194.689529      1.677558   
4       22461    544.584       192.801303       148.541136      1.297966   
...       ...        ...              ...              ...           ...   
13606   39956    745.166       273.867402       186.564001      1.467954   
13607  171914   1595.676       598.541646       368.358372      1.624889   
13608   48266    817.340       304.682706       202.282198      1.506226   
13609   43279    843.066       336.280446       164.667135      2.042183   
13610   46856    809.173       302.595376       197.920303      1.528875   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0          0.831018       45297     238.912806  0.658877  0.989690   0.848226   
1          0.769773       33907     206.453305  0.721155  0.987289   0.878921   
2          0.744491       27358     185.607226  0.801831  0.988998   0.925436   
3          0.802907       50289     251.005403  0.680179  0.983973   0.872348   
4          0.637517       22699     169.110122  0.774731  0.989515   0.951720   
...             ...         ...            ...       ...       ...        ...   
13606      0.732079       40504     225.551678  0.796000  0.986470   0.904244   
13607      0.788194      174673     467.854361  0.815980  0.984205   0.848461   
13608      0.747812       48780     247.899536  0.807232  0.989463   0.907916   
13609      0.871907       43813     234.743550  0.614566  0.987812   0.765181   
13610      0.756429       47372     244.251739  0.726900  0.989107   0.899275   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  
0         0.744899      0.007154      0.001359      0.554874      0.997534  
1         0.797616      0.007732      0.001930      0.636191      0.996669  
2         0.815996      0.008407      0.002299      0.665850      0.997330  
3         0.768534      0.006600      0.001420      0.590644      0.990840  
4         0.877121      0.008584      0.003134      0.769342      0.998579  
...            ...           ...           ...           ...           ...  
13606     0.823580      0.006854      0.001945      0.678284      0.995690  
13607     0.781657      0.003482      0.000802      0.610988      0.992788  
13608     0.813632      0.006313      0.001706      0.661997      0.997117  
13609     0.698059      0.007770      0.001138      0.487286      0.995128  
13610     0.807189      0.006458      0.001691      0.651555      0.996145  

[13611 rows x 16 columns]

In [67]:
hot=OneHotEncoder(sparse_output=False).fit_transform(df[['Class']])
X_train, X_test, y_train, y_test = train_test_split(X, hot, test_size=0.10, random_state=42, shuffle=True)


In [68]:
scaler = MinMaxScaler()
X_train_norm = scaler.fit_transform(X_train) 
X_test_norm  = scaler.transform(X_test)  

### Exercise 1.2 : Training and Testing the Neural Network (40 points)

Design a 3-layer (3 hidden layers and this does not include the input or output layer) artificial deep neural network, specifically a feed-forward multi-layer perceptron (using the sigmoid activation function), to classify the type of 'Dry Bean' given the other attributes in the data set, similar to the one mentioned in the paper above. Please note that this is a **multi-class classification** problem so select the right number of nodes accordingly for the input and output layers.

Consider the following hyperparameters while developing your model:

- Model type: Keras Sequential
- Make sure your input layer matches the size of your X matrix
- Number and type of hidden layers: 3 and Dense
- Number of nodes in each hidden layer: 12
- Learning rate should be 0.3
- Number of epochs should be 100
- The sigmoid function is to be used as the activation function in each layer
- Your output layer has to use a sigmoid function and the number of outputs should match the shape of your y
- Your loss function should be MSE
- Stochastic Gradient Descent should be used to minimize the error rate

**Note:** We are having you use MSE as your loss function for this model, is this a good choice? Why or why not? If not, what should you use instead in future models? Answer below

__Requirements once the model has been trained :__

- A confusion matrix for all classes, specifying the true positive, true negative, false positive, and false negative cases for each category in the class
- Since we do have OHE output (multi-class output) you will need to either reshape or argmax your outputs. Make sure they have already been thresholded as well i.e. look at yhat and do you see 1's and 0's?
- The accuracy and mean squared error (MSE) of the model
- The precision and recall for each label in the class

__Notes :__

- The mean squared error (MSE) values obtained __should be positive__.


In [69]:
!pip install tensorflow


[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: pip install --upgrade pip


In [70]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD


In [71]:
from tensorflow.keras import Input

In [72]:
model = Sequential([
    Input(shape=(X_train_norm.shape[1],)),
    Dense(12, activation="sigmoid"),
    Dense(12, activation="sigmoid"),
    Dense(12, activation="sigmoid"),
    Dense(y_train.shape[1], activation="sigmoid")
])

In [73]:
a = SGD(learning_rate=0.3)
model.compile(optimizer=a, loss="mse", metrics=["accuracy"])

In [74]:
model_train = model.fit(
    X_train_norm, y_train,
    epochs=100,
    verbose=0,
    validation_data=(X_test_norm, y_test)
)

In [75]:
y_pred = (model.predict(X_test_norm) > 0.5).astype(int)

43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


In [76]:
y_pred_classes = np.argmax(model.predict(X_test_norm), axis=1)
y_true_classes = np.argmax(y_test, axis=1)

43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 567us/step


In [77]:
from sklearn.metrics import confusion_matrix, classification_report

In [78]:
print(classification_report(y_true_classes, y_pred_classes))

              precision    recall  f1-score   support

           0       0.56      0.50      0.53       137
           1       0.00      0.00      0.00        63
           2       0.73      0.93      0.82       195
           3       0.83      0.97      0.89       342
           4       0.83      0.98      0.90       181
           5       0.91      0.95      0.93       200
           6       0.88      0.60      0.71       244

    accuracy                           0.80      1362
   macro avg       0.68      0.70      0.68      1362
weighted avg       0.77      0.80      0.78      1362



/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  

In [79]:
from sklearn.metrics import accuracy_score, mean_squared_error

In [80]:
mean_squared_error(y_true_classes, y_pred_classes)

1.1651982378854626

In [81]:
accuracy_score(y_true_classes,y_pred_classes)

0.8039647577092511

In [82]:
print(confusion_matrix(y_true_classes, y_pred_classes))

[[ 68   0  54   0   3   2  10]
 [ 49   0  14   0   0   0   0]
 [  5   0 181   0   7   1   1]
 [  0   0   0 331   0   7   4]
 [  0   0   0   2 178   0   1]
 [  0   0   0   5   0 191   4]
 [  0   0   0  63  27   8 146]]


## Exercise 2 : k-fold Cross Validation (20 points)

In order to avoid **using biased models**, use 10-fold cross validation to generalize the model from Ex1.2 on the given data set. You can choose a n_repeats value of 1-5

__Requirements :__
- Print the accuracy values during each iteration of the **cross validation** not the iterations per epoch or the epochs
- Print the overall average accuracy per each n_fold value, look at the documentation for the scoring parameter



In [83]:
from sklearn.model_selection import cross_val_score, KFold

In [ ]:
!pip install scikeras

In [85]:
from scikeras.wrappers import KerasClassifier

In [86]:
from sklearn.model_selection import RepeatedKFold, cross_val_score

In [87]:
def create_model(input_dim, output_dim):
    model = Sequential([
        Dense(12, activation="sigmoid", input_dim=input_dim),
        Dense(12, activation="sigmoid"),
        Dense(12, activation="sigmoid"),
        Dense(output_dim, activation="sigmoid")
    ])
    optimizer = SGD(learning_rate=0.3)
    model.compile(optimizer=optimizer, loss="mse", metrics=["accuracy"])
    return model

In [88]:
clf = KerasClassifier(
    model=create_model,
    model__input_dim=X_train_norm.shape[1],
    model__output_dim=y_train.shape[1],
    epochs=100,
    verbose=0
)

In [ ]:
!pip install --upgrade scikeras scikit-learn

In [91]:
for i in range(1):    
    kf = KFold(n_splits=10, shuffle=True)
    fold_accuracies = []
    for fold, (train_idx, val_idx) in enumerate(kf.split(X_train_norm), 1):
        print(f"Training fold {fold}...")
        X_tr, X_val = X_train_norm[train_idx], X_train_norm[val_idx]
        y_tr, y_val = y_train[train_idx], y_train[val_idx]
        model = create_model(X_train_norm.shape[1], y_train.shape[1])
        history = model.fit(X_tr, y_tr, epochs=100, verbose=0)
        loss, acc = model.evaluate(X_val, y_val, verbose=0)
        fold_accuracies.append(acc)
        print(f"Fold {fold} Accuracy: {acc:.4f}")
    print("\nAverage Accuracy across 10 folds:", np.mean(fold_accuracies))

Training fold 1...


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/layers/core/dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Fold 1 Accuracy: 0.6686
Training fold 2...
Fold 2 Accuracy: 0.4694
Training fold 3...
Fold 3 Accuracy: 0.5673
Training fold 4...
Fold 4 Accuracy: 0.5029
Training fold 5...
Fold 5 Accuracy: 0.5437
Training fold 6...
Fold 6 Accuracy: 0.5845
Training fold 7...
Fold 7 Accuracy: 0.5820
Training fold 8...
Fold 8 Accuracy: 0.5788
Training fold 9...
Fold 9 Accuracy: 0.7437
Training fold 10...
Fold 10 Accuracy: 0.5825

Average Accuracy across 10 folds: 0.5823332607746124


## Exercise 3 : Hyperparameter Tuning (25 points)

Use either grid search or random search methodology to find the optimal number of nodes required in each hidden layer, as well as the optimal learning rate and the different activation functions or optimization approaches, [keras_tuner examples](https://keras.io/guides/keras_tuner/getting_started/) such that the accuracy of the model is maximum for the given data set.

__Requirements :__
- The set of optimal hyperparameters
- Try your best to maximize accuracy using this set of optimal hyperparameters

__Note :__ Hyperparameter tuning takes a lot of time to execute. Make sure that you choose the appropriate number of each hyperparameter (preferably 3 of each), and that you allocate enough time to execute your code. Make sure to tune at least three parameters with three options each at a minimum, but feel free to experiment with more, just recognize that it will grow exponentially in running time

In [92]:
!pip install keras-tuner


[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: pip install --upgrade pip


In [ ]:
import keras_tuner as kt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD, Adam

def build_model(hp):
    model = Sequential()
    model.add(Dense(
        units=hp.Choice("units_layer1", [1, 3, 4]),
        activation=hp.Choice("activation", ["sigmoid", "relu", "tanh"]),
        input_dim=X_train_norm.shape[1]
    ))
    for i in range(2, 4):
        model.add(Dense(
            units=hp.Choice(f"units_layer{i}", [1, 3, 2]),
            activation=hp.Choice("activation", ["sigmoid", "relu", "tanh"])
        ))
    model.add(Dense(y_train.shape[1], activation="softmax"))
    learning_rate = hp.Choice("learning_rate", [0.01, 0.1, 0.3])
    optimizer_choice = hp.Choice("optimizer", ["sgd", "adam"])
    if optimizer_choice == "sgd":
        optimizer = SGD(learning_rate=learning_rate)
    else:
        optimizer = Adam(learning_rate=learning_rate)
    model.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=["accuracy"])
    return model

In [94]:
tuner = kt.RandomSearch(
    build_model,
    objective="val_accuracy",
    max_trials=2,        
    executions_per_trial=1,
    directory="my_dir",
    project_name="drybean_tuning"
)

tuner.search(X_train_norm, y_train, epochs=50, validation_data=(X_test_norm, y_test), verbose=0)

In [95]:
best_hp = tuner.get_best_hyperparameters(num_trials=1)[0]

print("Best hyperparameters:")
print("Layer 1 units:", best_hp.get("units_layer1"))
print("Layer 2 units:", best_hp.get("units_layer2"))
print("Layer 3 units:", best_hp.get("units_layer3"))
print("Activation:", best_hp.get("activation"))
print("Optimizer:", best_hp.get("optimizer"))
print("Learning rate:", best_hp.get("learning_rate"))

Best hyperparameters:
Layer 1 units: 3
Layer 2 units: 3
Layer 3 units: 3
Activation: tanh
Optimizer: adam
Learning rate: 0.01


In [96]:
best_model = tuner.hypermodel.build(best_hp)
history = best_model.fit(X_train_norm, y_train, epochs=100, validation_data=(X_test_norm, y_test), verbose=0)

loss, acc = best_model.evaluate(X_test_norm, y_test, verbose=0)
print("Test Accuracy with best hyperparameters:", acc)

Test Accuracy with best hyperparameters: 0.8935388922691345


## Exercise 4 - Collaborative Statement (5 points)

It is mandatory to include a Statement of Collaboration in each submission, that follows the guidelines below.
Include the names of everyone involved in the discussions (especially in-person ones), and what was discussed.
All students are required to follow the academic honesty guidelines posted on the course website. For
programming assignments in particular, I encourage students to organize (perhaps using Piazza) to discuss the
task descriptions, requirements, possible bugs in the support code, and the relevant technical content before they
start working on it. However, you should not discuss the specific solutions, and as a guiding principle, you are
not allowed to take anything written or drawn away from these discussions (no photographs of the blackboard,
written notes, referring to Piazza, etc.). Especially after you have started working on the assignment, try to restrict
the discussion to Piazza as much as possible, so that there is no doubt as to the extent of your collaboration.

Even if you did not use any outside resources or collaborate with anyone, please state that explicitly in the space below.

contributers= Zack Roland, Hungjun Doh, Gui 
Chatgpt: chatgpt was used throughout this enitre notebook to help me with how to implement the imports and models. 